### ISSUE TITLE
Codeforces and codechef solutions

### ISSUE THREAD

**Issue by LuciferJoshi** [strikersps/Competitive-Programming#1]
I want to contribute to this repositry by adding few codeforces and codechef solutions.

**Comment by strikersps** [comment]
Yeah you can contribute to this repository but follow the rules mentioned below:
1. Follow the coding conventions as described in the link https://wikileaks.org/ciav7p1/cms/page_26607644.html
2. Write an editorial for the solution in a Readme.md file.
3. When writing the code add the comment at the top of the source code which includes the following 2 thing's:
a. Problem Link
b. Author name. 

See I created this repository keeping in mind to write clean and understandable code with a good readme.md.

If you can follow the guidelines you are welcome to contribute.
